// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Optional: point at a scratch local Postgres db for `migrate dev`/`migrate diff`
    // in this non-interactive environment (CLI refuses interactive prompts here).
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
