name: Notify Slack on deploy

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🚀 Déploiement PROD\n\n> ${{ github.event.head_commit.message }}\n\n Commiter : ${{ github.event.head_commit.author.name }}\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
